name       : fluidsynth
version    : 2.1.4
release    : 21
source     :
    - https://github.com/FluidSynth/fluidsynth/archive/v2.1.4.tar.gz : 6e4f3e4a957d03812765bd0e400f61cd6c9fdb4bf10970e5cdaea8487d54b250
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Software synthesizer based on the SoundFont 2 specifications.
description: |
    FluidSynth is a real-time software synthesizer based on the Soundfont 2 specifications. It can be used for live audio synthesis of MIDI events or for rendering MIDI files to disk, using SoundFont instruments from SF2 and SF3 files. It can also be embedded in other applications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(lash-1.0)
    - pkgconfig(libpulse-simple)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - ladspa-devel
rundeps    :
    - ladspa
setup      : |
    %cmake_ninja -Denable-portaudio=1
build      : |
    %ninja_build
install    : |
    %ninja_install
