name       : fluidsynth
version    : 2.0.3
release    : 7
source     :
    - git|https://github.com/FluidSynth/fluidsynth.git : v2.0.3
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Software synthesizer based on the SoundFont 2 specifications.
description: |
    FluidSynth is a real-time software synthesizer based on the Soundfont 2 specifications. It can be used for live audio synthesis of MIDI events or for rendering MIDI files to disk, using SoundFont instruments. It can also be embedded in other applications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libpulse-simple)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
rundeps    :
    - jack-audio-connection-kit
    - ladspa
setup      : |
    mkdir build && pushd build
    %cmake -Denable-portaudio=1 \
           -Denable-ladspa=1 \
           -Denable-jack=1 \
           ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
