name       : fluidsynth
version    : 2.0.4
release    : 9
source     :
    - https://github.com/FluidSynth/fluidsynth/archive/v2.0.4.tar.gz : 2c065de87e9c9ba0311ebf2f4828a4fd76f1f5cc7d1d93dd80d7a048d7d2a76c
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Software synthesizer based on the SoundFont 2 specifications.
description: |
    FluidSynth is a real-time software synthesizer based on the Soundfont 2 specifications. It can be used for live audio synthesis of MIDI events or for rendering MIDI files to disk, using SoundFont instruments. It can also be embedded in other applications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libpulse-simple)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
rundeps    :
    - jack-audio-connection-kit
    - ladspa
setup      : |
    %cmake_ninja -Denable-portaudio=1
build      : |
    %ninja_build
install    : |
    %ninja_install
