name       : fluidsynth
version    : 1.1.6
release    : 1
source     :
    - https://sourceforge.net/projects/fluidsynth/files/fluidsynth-1.1.6/fluidsynth-1.1.6.tar.bz2/download : d28b47dfbf7f8e426902ae7fa2981d821fbf84f41da9e1b85be933d2d748f601
license    : LGPL-2.0
component  : multimedia.audio
summary    : A real-time software synthesizer based on the SoundFont 2 specifications.
description: |
    A real-time software synthesizer based on the SoundFont 2 specifications. It can be used for live audio synthesis of MIDI events or for rendering MIDI files to disk, using SoundFont instruments. It can also be embedded in other applications.
builddeps  :
    - pkgconfig(libpulse-simple)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(lash-1.0)
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
