name       : fluidsynth
version    : 1.1.10
release    : 4
source     :
    - https://github.com/FluidSynth/fluidsynth/archive/v1.1.10.tar.gz : b74801d0fdd726c4555149bf075b76dc4074658ec0a8f7a3753f4a64589e5300
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : A real-time software synthesizer based on the SoundFont 2 specifications.
description: |
    A real-time software synthesizer based on the SoundFont 2 specifications. It can be used for live audio synthesis of MIDI events or for rendering MIDI files to disk, using SoundFont instruments. It can also be embedded in other applications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse-simple)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
rundeps    :
    - ladspa
setup      : |
    mkdir build && pushd build
    %cmake -Denable-portaudio=1 \
           -Denable-ladspa=1 \
           -Denable-jack=0 \
           ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
